// Updated by the daily Outlook recruiting monitor. Keep this file valid JavaScript.
window.BB_SYNC_DATA = {
  version: 2026080901,
  checkedAt: "2026-08-09T09:12:46+08:00",
  correctedAt: "2026-08-09T09:12:46+08:00",
  summary: "Incremental and full reconciliation through 2026-08-09 09:12 HKT: J.P. Morgan confirmed receipt of the Markets video interview at 09:50 HKT on 2026-08-06; this was a correction to the prior pending state. Bank of America confirmed completion of the Global Investment Banking VI for application 4739429 at 15:04 HKT on 2026-08-08 and the Global Markets Sales & Trading Rotational VI for application 4757966 at 15:55 HKT; both were completed before their 16:55 and 16:10 HKT hard deadlines. Jefferies Investment Banking remains shortlisted for a first-round interview and is awaiting a coordination call. HSBC's OA remains due 2026-08-10 10:16 HKT. Tencent's comprehensive assessment remains expired from 2026-08-07 18:48 HKT. The 14-day company and keyword reconciliation found no other high-confidence changes; marketing, event, and generic recruitment emails were excluded.",
  applications: [
    { id: "ubs-gb", status: "VI Completed" },
    { id: "ubs-am", status: "VI Completed" },
    { id: "bofa-gib", status: "VI Completed", ref: "4739429" },
    { id: "gs-hk", status: "Applied", applied: "2026-07-31", logo: "assets/goldman-sachs.svg" },
    { id: "jpm-mkts", status: "VI Completed", ref: "210747060" },
    {
      id: "jpm-am",
      company: "JPMorgan",
      division: "Asset Management",
      role: "2027 Asset Management Program - Summer Internship",
      location: "Hong Kong",
      status: "VI Completed",
      applied: "2026-07-23",
      channel: "Oracle Careers",
      ref: "210743031",
      url: "",
      logo: "assets/jpmorgan.png"
    },
    {
      id: "jpm-gib",
      company: "JPMorgan",
      division: "Global Investment Banking",
      role: "2027 Summer Analyst",
      location: "Hong Kong",
      status: "VI Completed",
      applied: "2026-07-03",
      channel: "Oracle Careers",
      ref: "210749752",
      url: "",
      logo: "assets/jpmorgan.png"
    },
    {
      id: "jefferies-ib",
      company: "Jefferies",
      division: "Investment Banking",
      role: "2027 Summer Analyst Program",
      location: "Hong Kong",
      status: "Interview Pending",
      applied: "2026-06-29",
      channel: "Jefferies Careers",
      ref: "",
      url: "",
      logo: "assets/jefferies.png"
    },
    {
      id: "gs-application-20260730",
      company: "Goldman Sachs",
      division: "Programme not stated in confirmation",
      role: "Application received · submitted 2026-07-30",
      location: "",
      status: "Applied",
      applied: "2026-07-30",
      channel: "Goldman Sachs Careers",
      ref: "",
      url: "",
      logo: "assets/goldman-sachs.svg"
    },
    {
      id: "gs-application-20260731-1000",
      company: "Goldman Sachs",
      division: "Programme not stated in confirmation",
      role: "Application received · confirmation at 10:00 HKT",
      location: "",
      status: "Applied",
      applied: "2026-07-31",
      channel: "Goldman Sachs Careers",
      ref: "",
      url: "",
      logo: "assets/goldman-sachs.svg"
    },
    {
      id: "gs-application-20260731-1120",
      company: "Goldman Sachs",
      division: "Programme not stated in confirmation",
      role: "Application received · confirmation at 11:20 HKT",
      location: "",
      status: "Applied",
      applied: "2026-07-31",
      channel: "Goldman Sachs Careers",
      ref: "",
      url: "",
      logo: "assets/goldman-sachs.svg"
    },
    {
      id: "ms-ib",
      company: "Morgan Stanley",
      division: "Investment Banking",
      role: "2027 Investment Banking Industrial Placement / Summer Analyst Program",
      location: "Hong Kong / Singapore / Seoul",
      status: "Applied",
      applied: "2026-08-01",
      channel: "Morgan Stanley Careers",
      ref: "",
      url: "",
      logo: "assets/morgan-stanley.svg"
    },
    {
      id: "ms-ied-2027-hk-sg",
      company: "Morgan Stanley",
      division: "Institutional Equity Division",
      role: "2027 Institutional Equity Division Industrial Placement / Summer Analyst Program",
      location: "Hong Kong / Singapore",
      status: "Applied",
      applied: "2026-07-31",
      channel: "Morgan Stanley Careers",
      ref: "",
      url: "",
      logo: "assets/morgan-stanley.svg"
    },
    {
      id: "ms-gcm-2027-hk",
      company: "Morgan Stanley",
      division: "Global Capital Markets",
      role: "2027 Global Capital Markets Industrial Placement / Summer Analyst Program",
      location: "Hong Kong",
      status: "Applied",
      applied: "2026-08-01",
      channel: "Morgan Stanley Careers",
      ref: "",
      url: "",
      logo: "assets/morgan-stanley.svg"
    },
    {
      id: "hsbc-investment-banking-internship",
      company: "HSBC",
      division: "Investment Banking",
      role: "Investment Banking - Internship",
      location: "",
      status: "OT Pending",
      applied: "2026-07-28",
      channel: "HSBC Careers",
      ref: "",
      url: "",
      logo: "assets/hsbc.svg"
    },
    {
      id: "citi-markets-st-2027-hk",
      company: "Citi",
      division: "Markets · Sales and Trading",
      role: "2027 Summer Analyst",
      location: "Hong Kong",
      status: "Questionnaire Pending",
      applied: "2026-07-29",
      channel: "Citi Workday",
      ref: "26978275",
      url: "",
      logo: "assets/citi.svg"
    },
    {
      id: "barclays-investment-banking-summer-internship",
      company: "Barclays",
      division: "Investment Banking",
      role: "Investment Banking Summer Internship Programme",
      location: "",
      status: "Withdrawn",
      applied: "2026-07-30",
      channel: "Barclays Workday",
      ref: "JR-0000117558",
      url: "",
      logo: "assets/barclays.svg"
    },
    {
      id: "bofa-4757966",
      company: "Bank of America",
      division: "Global Markets · Sales & Trading Rotational",
      role: "Global Markets Sales & Trading Rotational Summer Analyst - 2027",
      location: "",
      status: "VI Completed",
      applied: "2026-07-29",
      channel: "BofA Campus Careers",
      ref: "4757966",
      url: "",
      logo: "assets/bofa.png"
    },
    {
      id: "tencent-unspecified-2027",
      company: "Tencent",
      division: "Programme not stated in assessment email",
      role: "Application received · programme not stated",
      location: "",
      status: "OT Expired",
      applied: "2026-08-05",
      channel: "Tencent Careers",
      ref: "",
      url: "",
      logo: ""
    }
  ],
  assessments: [
    {
      id: "hsbc-investment-banking-ot",
      appId: "hsbc-investment-banking-internship",
      type: "OT",
      platform: "HSBC Online Immersive Assessment",
      status: "Not Started",
      received: "2026-07-31T10:16",
      deadline: "2026-08-10T10:16",
      original: "Next step: your HSBC Online Immersive Assessment; received 2026-07-31 10:16 HKT for Investment Banking - Internship; email states 'You have 10 days to complete the assessment'; not timed once started and usually takes about 50 minutes",
      urgency: "warning"
    },
    {
      id: "ubs-gb-vi",
      appId: "ubs-gb",
      type: "VI",
      platform: "HireVue",
      status: "Confirmed",
      received: "2026-07-24T18:08",
      deadline: "2026-07-31T18:08",
      original: "completion confirmed by email on 2026-07-27 05:44 HKT",
      urgency: "done"
    },
    {
      id: "ubs-am-vi",
      appId: "ubs-am",
      type: "VI",
      platform: "HireVue",
      status: "Confirmed",
      received: "2026-07-27T08:20",
      deadline: "2026-08-03T08:20",
      original: "seven calendar days (168 hours to be exact); completion confirmation received 2026-08-02 23:00 HKT stating the video interview was received",
      urgency: "done"
    },
    {
      id: "jpm-am-vi",
      appId: "jpm-am",
      type: "VI",
      platform: "HireVue",
      status: "Confirmed",
      received: "2026-07-23T09:45",
      deadline: "",
      original: "2027 Asset Management Summer Analyst Program - Hong Kong; completion confirmation received 2026-08-06 08:53 HKT stating 'Thanks for submitting your video'; no official deadline stated",
      urgency: "done"
    },
    {
      id: "jpm-mkts-vi",
      appId: "jpm-mkts",
      type: "VI",
      platform: "HireVue",
      status: "Confirmed",
      received: "2026-07-23T09:50",
      deadline: "",
      original: "Reminder received 2026-07-30 21:51 HKT for 2027 Commercial & Investment Bank - Markets Summer Analyst Program - Hong Kong, 210747060; completion confirmation received 2026-08-06 09:50 HKT stating 'Thanks for submitting your video'; submit at the soonest on a rolling basis; no official deadline stated",
      urgency: "done"
    },
    {
      id: "citi-markets-questionnaire",
      appId: "citi-markets-st-2027-hk",
      type: "Questionnaire",
      platform: "Citi Workday",
      status: "Not Started",
      received: "2026-07-29T05:41",
      deadline: "",
      original: "Complete Questionnaire; Campus Job App Template – APAC; Campus Job Submission - Global; no deadline stated in the emails",
      urgency: "warning"
    },
    {
      id: "barclays-investment-banking-ot",
      appId: "barclays-investment-banking-summer-internship",
      type: "OT",
      platform: "Barclays Online Assessment",
      status: "Expired",
      received: "2026-07-30T06:51:00+08:00",
      deadline: "2026-08-04T06:51:00+08:00",
      original: "Email states: You have 5 calendar days (or before the close date of your application, if applicable) to complete this stage; received 2026-07-30 06:51 HKT",
      urgency: "danger"
    },
    {
      id: "bofa-ot",
      appId: "bofa-gib",
      type: "OT",
      platform: "BofA Assessment",
      status: "Confirmed",
      received: "2026-07-21T02:55",
      deadline: "2026-07-24T02:55",
      original: "ASSESSMENT COMPLETE confirmation received 2026-07-21 04:24 HKT",
      urgency: "done"
    },
    {
      id: "bofa-gib-vi",
      appId: "bofa-gib",
      type: "VI",
      platform: "Bank of America Video Interview",
      status: "Confirmed",
      received: "2026-08-05T16:55:00+08:00",
      deadline: "2026-08-08T16:55:00+08:00",
      original: "Application ID 4739429 · Global Investment Banking Summer Analyst - 2027 - Hong Kong · email states complete no later than 3 days (72 hours) from the exact time of the invitation; completion confirmation received 2026-08-08 15:04 HKT stating the interview was received",
      urgency: "done"
    },
    {
      id: "bofa-4757966-vi",
      appId: "bofa-4757966",
      type: "VI",
      platform: "Bank of America Video Interview",
      status: "Confirmed",
      received: "2026-08-05T16:10:00+08:00",
      deadline: "2026-08-08T16:10:00+08:00",
      original: "Application ID 4757966 · Global Markets Sales & Trading Rotational Summer Analyst - 2027 - Hong Kong · email states complete no later than 3 days (72 hours) from the exact time of the invitation; completion confirmation received 2026-08-08 15:55 HKT stating the interview was received",
      urgency: "done"
    },
    {
      id: "tencent-comprehensive-assessment",
      appId: "tencent-unspecified-2027",
      type: "OT",
      platform: "Tencent 综合素质测评",
      status: "Expired",
      received: "2026-08-05T18:48:00+08:00",
      deadline: "2026-08-07T18:48:00+08:00",
      original: "已过期 · 腾讯邮件正文写明：感谢投递腾讯，开始进入综合素质测评环节；烦请在收到邮件48小时内完成测评；岗位或 programme 未在邮件中说明",
      urgency: "danger"
    }
  ],
  calendarTasks: [
    {
      id: "cal-hsbc-investment-banking-ot-follow-up",
      date: "2026-08-04",
      time: "10:00",
      title: "完成 HSBC Online Immersive Assessment",
      shortTitle: "HSBC IBD OA",
      category: "OT",
      assessmentId: "hsbc-investment-banking-ot",
      note: "邀请于 2026-07-31 10:16 HKT 收到 · 邮件明确要求 10 天内完成 · 官方截止 2026-08-10 10:16 HKT · 开始后不计时，预计约 50 分钟"
    },
    {
      id: "cal-ubs-am-vi",
      date: "2026-08-02",
      time: "18:00",
      title: "完成 UBS Asset Management VI",
      shortTitle: "UBS AM VI",
      category: "VI",
      assessmentId: "ubs-am-vi",
      note: "2026-08-02 23:00 HKT 收到 HireVue 完成确认",
      done: true
    },
    {
      id: "cal-gs-hk-submit-application",
      date: "2026-07-31",
      time: "10:30",
      title: "完成并提交 Goldman Sachs IBD Summer Analyst 申请",
      shortTitle: "GS IBD 申请草稿",
      category: "Application",
      note: "2026-07-31 08:55 收到正式 application confirmation；邮件本身未写岗位名，按此前 IBD Summer Analyst 草稿关联",
      done: true
    },
    {
      id: "cal-jpm-mkts",
      date: "2026-08-03",
      time: "11:30",
      title: "完成 JPM CIB Markets VI",
      shortTitle: "JPM Markets VI",
      category: "VI",
      assessmentId: "jpm-mkts-vi",
      note: "2026-07-30 21:51 收到 reminder；2026-08-06 09:50 HKT 收到完成确认；官方仅写 ASAP / rolling basis，无明确截止",
      done: true
    },
    {
      id: "cal-jpm-am",
      date: "2026-08-03",
      time: "10:00",
      title: "完成 JPM Asset Management VI",
      shortTitle: "JPM AM VI",
      category: "VI",
      assessmentId: "jpm-am-vi",
      note: "2026-08-06 08:53 HKT 收到 J.P. Morgan 完成确认：We've received your video；原邀请要求 ASAP，无明确官方截止",
      done: true
    },
    {
      id: "cal-citi-workday-review",
      date: "2026-08-03",
      time: "14:00",
      title: "完成 Citi 的 3 个 Workday tasks",
      shortTitle: "Citi questionnaire",
      category: "Questionnaire",
      assessmentId: "citi-markets-questionnaire",
      note: "包含 Complete Questionnaire、APAC application template、Global submission；未注明官方截止"
    },
    {
      id: "cal-barclays-account-verify",
      date: "2026-07-29",
      time: "12:30",
      title: "验证 Barclays candidate account",
      shortTitle: "Barclays account",
      category: "Application",
      note: "仅为候选人账户验证，不计作已申请；邮件未注明官方截止",
      done: true
    },
    {
      id: "cal-barclays-investment-banking-ot",
      date: "2026-08-04",
      time: "06:51",
      title: "完成 Barclays Investment Banking online assessment",
      shortTitle: "Barclays IB OT",
      category: "OT",
      assessmentId: "barclays-investment-banking-ot",
      note: "已过期 · 邮件明确写 5 calendar days；按 2026-07-30 06:51 HKT 收件时间换算，hard deadline 为 2026-08-04 06:51 HKT",
      hardDeadline: true,
      status: "Expired",
      closed: true
    },
    {
      id: "cal-bofa-4757966-programme",
      date: "2026-08-02",
      time: "12:00",
      title: "在 BofA portal 核对 4757966 的岗位名称",
      shortTitle: "核对 BofA 4757966",
      category: "Application",
      note: "8 月 2 日已按申请号搜索 Outlook 所有文件夹：仅找到 7 月 29 日收件确认，没有 programme 或后续状态邮件；不要与 GIB 4739429 合并"
    },
    {
      id: "cal-gs-programme-mapping",
      date: "2026-08-03",
      time: "18:00",
      title: "在 Goldman Sachs portal 映射 4 条申请的 programme",
      shortTitle: "核对 GS 4 条申请",
      category: "Application",
      note: "邮箱找到 7 月 30 日 1 封、7 月 31 日 08:55、10:00、11:20 共 4 封申请确认；确认邮件均未显示岗位名称"
    },
    {
      id: "cal-bofa-gib-vi",
      date: "2026-08-08",
      time: "16:55",
      title: "完成 Bank of America Global Investment Banking VI",
      shortTitle: "BofA GIB VI",
      category: "VI",
      assessmentId: "bofa-gib-vi",
      note: "邀请于 2026-08-05 16:55 HKT 收到；正文写明 3 days (72 hours) from the exact time of invitation，hard deadline 为 2026-08-08 16:55 HKT；完成确认于 2026-08-08 15:04 HKT 收到",
      hardDeadline: true,
      done: true
    },
    {
      id: "cal-bofa-4757966-vi",
      date: "2026-08-08",
      time: "16:10",
      title: "完成 Bank of America Global Markets Sales & Trading VI",
      shortTitle: "BofA Global Markets VI",
      category: "VI",
      assessmentId: "bofa-4757966-vi",
      note: "邀请于 2026-08-05 16:10 HKT 收到；正文写明 3 days (72 hours) from the exact time of invitation，hard deadline 为 2026-08-08 16:10 HKT；完成确认于 2026-08-08 15:55 HKT 收到",
      hardDeadline: true,
      done: true
    },
    {
      id: "cal-tencent-comprehensive-assessment",
      date: "2026-08-07",
      time: "18:48",
      title: "完成腾讯综合素质测评",
      shortTitle: "腾讯综合测评",
      category: "OT",
      assessmentId: "tencent-comprehensive-assessment",
      note: "已过期 · 邮件于 2026-08-05 18:48 HKT 收到；正文写明收到邮件 48 小时内完成，hard deadline 为 2026-08-07 18:48 HKT；programme 未在邮件中说明",
      hardDeadline: true,
      status: "Expired",
      closed: true
    }
  ]
};
