import { escapeHtml, formatDateTime, statusClass } from "../shared/utils.js";

let outlet;
let onClick;
function render() {
  const state = window.BBStore.getSnapshot();
  const apps = Object.fromEntries(state.applications.map(app => [app.id, app]));
  const pending = state.assessments.filter(item => !["Confirmed", "Completed", "Submitted", "Expired"].includes(item.status));
  const completed = state.assessments.filter(item => ["Confirmed", "Completed", "Submitted"].includes(item.status));
  const ended = state.assessments.filter(item => ["Confirmed", "Completed", "Submitted", "Expired"].includes(item.status));
  const card = item => { const app = apps[item.applicationId || item.appId] || {}; const task = state.tasks.find(taskItem => taskItem.assessmentId === item.id); const hasOfficial = Boolean(item.deadline); const expired = item.status === "Expired" || (hasOfficial && new Date(item.deadline) < new Date() && !completed.includes(item)); return `<article class="record-row"><div><div class="record-main"><span class="status-badge ${statusClass(item.status)}">${escapeHtml(item.type)}</span><div><strong>${escapeHtml(app.company || "未知公司")} · ${escapeHtml(app.division || app.role || "Programme 未标明")}</strong><div class="meta">${escapeHtml(item.platform || "Assessment")} · ${escapeHtml(item.status)}${task?.done ? " · task done" : ""}</div></div></div><div class="meta" style="margin-left:45px">${hasOfficial ? `官方 deadline：${escapeHtml(formatDateTime(item.deadline))}` : "没有官方 deadline"} · ${item.original ? escapeHtml(item.original) : ""}</div></div><div class="actions">${expired ? `<span class="status-badge danger">已过期</span>` : hasOfficial ? `<span class="status-badge pending">官方截止</span>` : `<span class="status-badge pending">建议尽快</span>`}${["Confirmed", "Completed", "Submitted"].includes(item.status) ? `<span class="status-badge done">已完成</span>` : item.status === "Expired" ? "" : `<button class="button primary" data-confirm-assessment="${escapeHtml(item.id)}">确认已完成</button>`}</div></article>`; };
  outlet.innerHTML = `<div class="page-intro"><div><h2>OT / VI</h2><p>邀请、官方 deadline、建议完成日和用户确认分开显示。</p></div><div class="small muted">${pending.length} 项待处理 · ${completed.length} 项已确认</div></div>
    <div class="v2-grid"><section class="v2-card span-7"><div class="v2-card-head"><div><h3>未完成 / 待确认</h3><span class="small muted">邀请不会自动变成完成</span></div></div><div class="record-list">${pending.map(card).join("") || `<div class="empty"><strong>没有未完成测评</strong>以邮件确认或用户确认作为完成依据。</div>`}</div></section><section class="v2-card span-5"><div class="v2-card-head"><div><h3>完成 / 已结束</h3><span class="small muted">完成与过期明确区分</span></div></div><div class="record-list">${ended.map(card).join("") || `<div class="empty">暂无</div>`}</div></section><section class="v2-card span-12"><div class="v2-card-head"><h3>规则</h3></div><div class="v2-card-body"><div class="gap-list"><div class="gap-item">官方 deadline：必须打开邮件正文核对，不能只读预览。</div><div class="gap-item">ASAP / rolling：只显示建议完成，不伪造官方截止。</div><div class="gap-item">确认已完成：会同时更新 Assessment、Application、Task 和日历。</div></div></div></section></div>`;
}
export function mount(target) { outlet = target; render(); onClick = event => { const button = event.target.closest("[data-confirm-assessment]"); if (button) window.BBStore.dispatch({ type: "assessment.completed", assessmentId: button.dataset.confirmAssessment, source: "user" }); }; outlet.addEventListener("click", onClick); }
export function unmount() { outlet?.removeEventListener("click", onClick); outlet = null; onClick = null; }
