import { escapeHtml, formatDate } from "../shared/utils.js";

let outlet;
let onClick;
let cursor = new Date();
let selected = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Hong_Kong" }).format(new Date());
const key = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
function monthDays(date) { const first = new Date(date.getFullYear(), date.getMonth(), 1, 12); const start = new Date(first); start.setDate(first.getDate() - first.getDay()); return Array.from({ length: 42 }, (_, index) => { const day = new Date(start); day.setDate(start.getDate() + index); return day; }); }
function render() {
  const state = window.BBStore.getSnapshot();
  const days = monthDays(cursor);
  const events = state.tasks.reduce((map, task) => { if (task.date) (map[task.date] ||= []).push(task); return map; }, {});
  const selectedTasks = (events[selected] || []).sort((a, b) => `${a.time}`.localeCompare(`${b.time}`));
  const monthLabel = new Intl.DateTimeFormat("zh-Hans-HK", { year: "numeric", month: "long", timeZone: "Asia/Hong_Kong" }).format(cursor);
  outlet.innerHTML = `<div class="page-intro"><div><h2>日历</h2><p>申请流程和每天的准备任务共用一条 Task 数据，不再有第二份日程状态。</p></div><div class="small muted">${state.tasks.filter(task => !task.done && !task.closed).length} 项未完成</div></div><div class="calendar-shell"><section class="v2-card calendar-large"><div class="v2-card-head"><div><h3>${escapeHtml(monthLabel)}</h3><span class="small muted">点击日期查看当天安排</span></div><div class="calendar-controls"><button class="icon-button" data-month="-1" title="上个月">‹</button><button class="calendar-today" data-calendar-today>今天</button><button class="icon-button" data-month="1" title="下个月">›</button></div></div><div class="calendar-weekdays"><span>日</span><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span></div><div class="calendar-grid">${days.map(day => { const dayKey = key(day); const dayEvents = events[dayKey] || []; const outside = day.getMonth() !== cursor.getMonth(); const today = dayKey === new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Hong_Kong" }).format(new Date()); return `<button class="calendar-day ${outside ? "outside" : ""} ${dayKey === selected ? "selected" : ""} ${today ? "today" : ""}" data-date="${dayKey}"><span class="day-number">${day.getDate()}</span><div class="event-dots">${dayEvents.slice(0, 4).map(event => `<i class="event-dot cat-${String(event.category || "task").toLowerCase()} ${event.hardDeadline ? "hard" : ""}"></i>`).join("")}</div>${dayEvents.slice(0, 2).map(event => `<span class="event-preview">${escapeHtml(event.shortTitle || event.title)}</span>`).join("")}${dayEvents.length > 2 ? `<small>+${dayEvents.length - 2}</small>` : ""}</button>`; }).join("")}</div><div class="calendar-legend"><span><i class="event-dot cat-ot"></i> OT</span><span><i class="event-dot cat-vi"></i> VI</span><span><i class="event-dot cat-resume"></i> 简历</span><span><i class="event-dot cat-project"></i> 项目</span><span><i class="event-dot hard"></i> 官方截止</span></div></section><aside class="v2-card agenda-side"><div class="v2-card-head"><div><h3>${escapeHtml(formatDate(selected))}</h3><span class="small muted">当天安排</span></div><span class="small muted">${selectedTasks.length} 项</span></div><div class="record-list">${selectedTasks.map(task => `<div class="record-row ${task.done ? "done" : ""}"><div><strong>${escapeHtml(task.title)}</strong><div class="meta">${escapeHtml(task.time || "待安排")} · ${escapeHtml(task.note || task.category || "")}</div></div><div class="actions">${task.closed ? `<span class="status-badge danger">已过期</span>` : `<span class="status-badge ${task.done ? "done" : "pending"}">${task.done ? "完成" : escapeHtml(task.category || "Task")}</span><button class="icon-button" data-task="${escapeHtml(task.id)}" title="${task.done ? "恢复任务" : "标记完成"}">${task.done ? "✓" : "○"}</button>`}</div></div>`).join("") || `<div class="empty"><strong>当天没有任务</strong>可以在准备页面继续整理素材。</div>`}</div></aside></div>`;
}
export function mount(target) { outlet = target; render(); onClick = event => { const date = event.target.closest("[data-date]"); if (date) { selected = date.dataset.date; const parsed = new Date(`${selected}T12:00:00`); cursor = new Date(parsed.getFullYear(), parsed.getMonth(), 1, 12); render(); return; } const month = event.target.closest("[data-month]"); if (month) { cursor = new Date(cursor.getFullYear(), cursor.getMonth() + Number(month.dataset.month), 1, 12); render(); return; } if (event.target.closest("[data-calendar-today]")) { cursor = new Date(); selected = key(cursor); render(); return; } const task = event.target.closest("[data-task]"); if (task) { const snapshot = window.BBStore.getSnapshot(); const current = snapshot.tasks.find(item => item.id === task.dataset.task); window.BBStore.dispatch({ type: "task.completed", taskId: task.dataset.task, done: !current?.done }); } }; outlet.addEventListener("click", onClick); }
export function unmount() { outlet?.removeEventListener("click", onClick); outlet = null; onClick = null; }
